### ISSUE TITLE
Won't connect to broker, no output

### ISSUE THREAD

**Issue by Garulf** [Legion2/open-cue-mqtt#42]
Try as I might I can't seem to get this to work.

Config:
```
broker.url=tcp://10.0.0.12:1883
broker.username=garulf
broker.password=PASSWORD
mqtt.topic.profile=home/open-cue-mqtt/profile
mqtt.topic.sdk=home/open-cue-mqtt/sdk
```
![image](https://user-images.githubusercontent.com/535299/150756292-be9e1bac-9616-4f6b-abc7-06251c653e34.png)

Maybe you can point me to what I may be doing wrong?

**Comment by Legion2** [comment]
do you have java installed, do you see something in the logs of the mqtt broker?

**Comment by Garulf** [comment]
Java for windows is installed.

Mosquitto log:
```
2021/09/24 13:32:26     Granting 'sc-mosquitto' unix ownership on /volume1/@appstore/mosquitto/var
2021/09/24 13:32:26     upgrade mosquitto 1.6.15-12 End postupgrade ret=[0]
2021/09/24 13:32:32     upgrade mosquitto 1.6.15-12 Begin start-stop-status start
2021/09/24 13:32:33     upgrade mosquitto 1.6.15-12 End start-stop-status start ret=[0]
2021/09/24 13:32:33     upgrade mosquitto 1.6.15-12 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2021/09/24 13:32:33     upgrade mosquitto 1.6.15-12 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2021/10/27 15:55:01     (system) trigger mosquitto 1.6.15-12 Begin start-stop-status stop
2021/10/27 15:55:02     (system) trigger mosquitto 1.6.15-12 End start-stop-status stop ret=[0]
2021/10/27 18:47:00     (system) trigger mosquitto 1.6.15-12 Begin start-stop-status start
2021/10/27 18:47:02     (system) trigger mosquitto 1.6.15-12 End start-stop-status start ret=[0]



```

![image](https://user-images.githubusercontent.com/535299/150759127-90253e25-7b2f-4a4f-971a-eb00cb91f797.png)

**Comment by Legion2** [comment]
Which Windows version do you use? I only tested 10

**Comment by Garulf** [comment]
```
Edition	Windows 10 Home
Version	21H1
Installed on	‎8/‎5/‎2021
OS build	19043.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0
```

**Comment by Legion2** [comment]
I can look at it later when I'm at my windows machine

**Comment by Garulf** [comment]
> I can look at it later when I'm at my windows machine

Thank you I'd appreciate it. Is there some sort of log that I can check for errors?

**Comment by Legion2** [comment]
you can change your config to force a config parse error, to see where it hangs

**Comment by Garulf** [comment]
> you can change your config to force a config parse error, to see where it hangs

I'm not sure what it's doing. Seemingly it's connected but not sending the messages for some reason.

**Comment by Legion2** [comment]
You know, you also have to use and run open-cue-service and the mqtt adapter only receives messages and do not send any to the mqtt Broker.

**Comment by Garulf** [comment]
> You know, you also have to use and run open-cue-service and the mqtt adapter only receives messages and do not send any to the mqtt Broker.

That was it! I was expecting a topic of the current profile. But yes sending a message does work:
![image](https://user-images.githubusercontent.com/535299/151632436-97a675af-b5af-4584-a45a-1f804ce8410f.png)
